In [33]:
import numpy as np
import re
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error


# Data Preprocessing 
dataset = pd.read_csv("../Datasets/Iris.csv")


In [42]:
X = dataset.drop(["Id","Species","SepalWidthCm"],axis=1 )
y = dataset["SepalWidthCm"]

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size = 0.2, random_state = 25)
X_validation, X_test,y_validation, y_test = train_test_split(X_test,y_test, test_size = 0.5,random_state = 25)
len(X_train)

120

In [44]:
class Linear:

    def __init__(self):
        self = self
        
    def fit(self, X, y):
        leftmat = np.linalg.inv(X.T @ X)
        self.betas = leftmat @ X.T @ y
    
    def predict(self, X):
        return X @ self.betas

In [45]:
clf = Linear()
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

In [46]:
pred 

array([2.6032262 , 3.76272582, 2.72499629, 2.5398257 , 3.17708481,
       3.07205637, 3.50965686, 3.1006551 , 3.55217322, 2.82630929,
       3.18129598, 2.69636323, 2.75498217, 3.01283269, 3.32802102])

In [47]:
y_test

array([2.7, 3.4, 3.2, 2.3, 3.1, 2.8, 3.7, 3.4, 3.4, 3. , 3.8, 2.8, 2.8,
       3.2, 3.1])

In [48]:

total = 0
for i in range(len(pred)):
    total+= (abs(pred[i]-y_test[i]))**2

In [49]:
print(f"the mse is {total/(len(pred))}")

the mse is 0.07771912602738484


In [15]:
beta = (np.linalg.inv(X_train.T @ X_train))@ X_train.T @ y_train

In [16]:
X_test@beta

array([2.6032262 , 3.76272582, 2.72499629, 2.5398257 , 3.17708481,
       3.07205637, 3.50965686, 3.1006551 , 3.55217322, 2.82630929,
       3.18129598, 2.69636323, 2.75498217, 3.01283269, 3.32802102])